# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prefix_server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='prefix_server.proto',
  package='models',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13prefix_server.proto\x12\x06models\x1a\x1bgoogle/protobuf/empty.proto\"B\n\x06\x44\x42Item\x12\r\n\x05tx_id\x18\x01 \x01(\x0c\x12\x13\n\x0binput_index\x18\x02 \x01(\r\x12\x14\n\x0c\x62lock_height\x18\x03 \x01(\r\"A\n\x04Item\x12\x0e\n\x06raw_tx\x18\x01 \x01(\x0c\x12\x13\n\x0binput_index\x18\x02 \x01(\r\x12\x14\n\x0c\x62lock_height\x18\x03 \x01(\r\"+\n\rBlockInterval\x12\r\n\x05start\x18\x02 \x01(\r\x12\x0b\n\x03\x65nd\x18\x03 \x01(\r\"G\n\x0cSearchParams\x12\x0e\n\x06prefix\x18\x01 \x01(\x0c\x12\'\n\x08interval\x18\x02 \x01(\x0b\x32\x15.models.BlockInterval\"\x7f\n\x0cServerStatus\x12/\n\x05state\x18\x01 \x01(\x0e\x32 .models.ServerStatus.ServerState\x12\x17\n\x0fscrape_position\x18\x02 \x01(\r\"%\n\x0bServerState\x12\x08\n\x04IDLE\x10\x00\x12\x0c\n\x08SCRAPING\x10\x01\x32@\n\x06Public\x12\x36\n\x0cPrefixSearch\x12\x14.models.SearchParams\x1a\x0c.models.Item\"\x00\x30\x01\x32~\n\x07Private\x12\x39\n\x06Scrape\x12\x15.models.BlockInterval\x1a\x16.google.protobuf.Empty\"\x00\x12\x38\n\x06Status\x12\x16.google.protobuf.Empty\x1a\x14.models.ServerStatus\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])



_SERVERSTATUS_SERVERSTATE = _descriptor.EnumDescriptor(
  name='ServerState',
  full_name='models.ServerStatus.ServerState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCRAPING', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=403,
  serialized_end=440,
)
_sym_db.RegisterEnumDescriptor(_SERVERSTATUS_SERVERSTATE)


_DBITEM = _descriptor.Descriptor(
  name='DBItem',
  full_name='models.DBItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tx_id', full_name='models.DBItem.tx_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_index', full_name='models.DBItem.input_index', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_height', full_name='models.DBItem.block_height', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=126,
)


_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='models.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_tx', full_name='models.Item.raw_tx', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_index', full_name='models.Item.input_index', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_height', full_name='models.Item.block_height', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=193,
)


_BLOCKINTERVAL = _descriptor.Descriptor(
  name='BlockInterval',
  full_name='models.BlockInterval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='models.BlockInterval.start', index=0,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='models.BlockInterval.end', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=238,
)


_SEARCHPARAMS = _descriptor.Descriptor(
  name='SearchParams',
  full_name='models.SearchParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prefix', full_name='models.SearchParams.prefix', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interval', full_name='models.SearchParams.interval', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=311,
)


_SERVERSTATUS = _descriptor.Descriptor(
  name='ServerStatus',
  full_name='models.ServerStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='models.ServerStatus.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scrape_position', full_name='models.ServerStatus.scrape_position', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SERVERSTATUS_SERVERSTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=440,
)

_SEARCHPARAMS.fields_by_name['interval'].message_type = _BLOCKINTERVAL
_SERVERSTATUS.fields_by_name['state'].enum_type = _SERVERSTATUS_SERVERSTATE
_SERVERSTATUS_SERVERSTATE.containing_type = _SERVERSTATUS
DESCRIPTOR.message_types_by_name['DBItem'] = _DBITEM
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['BlockInterval'] = _BLOCKINTERVAL
DESCRIPTOR.message_types_by_name['SearchParams'] = _SEARCHPARAMS
DESCRIPTOR.message_types_by_name['ServerStatus'] = _SERVERSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DBItem = _reflection.GeneratedProtocolMessageType('DBItem', (_message.Message,), {
  'DESCRIPTOR' : _DBITEM,
  '__module__' : 'prefix_server_pb2'
  # @@protoc_insertion_point(class_scope:models.DBItem)
  })
_sym_db.RegisterMessage(DBItem)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
  'DESCRIPTOR' : _ITEM,
  '__module__' : 'prefix_server_pb2'
  # @@protoc_insertion_point(class_scope:models.Item)
  })
_sym_db.RegisterMessage(Item)

BlockInterval = _reflection.GeneratedProtocolMessageType('BlockInterval', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKINTERVAL,
  '__module__' : 'prefix_server_pb2'
  # @@protoc_insertion_point(class_scope:models.BlockInterval)
  })
_sym_db.RegisterMessage(BlockInterval)

SearchParams = _reflection.GeneratedProtocolMessageType('SearchParams', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHPARAMS,
  '__module__' : 'prefix_server_pb2'
  # @@protoc_insertion_point(class_scope:models.SearchParams)
  })
_sym_db.RegisterMessage(SearchParams)

ServerStatus = _reflection.GeneratedProtocolMessageType('ServerStatus', (_message.Message,), {
  'DESCRIPTOR' : _SERVERSTATUS,
  '__module__' : 'prefix_server_pb2'
  # @@protoc_insertion_point(class_scope:models.ServerStatus)
  })
_sym_db.RegisterMessage(ServerStatus)



_PUBLIC = _descriptor.ServiceDescriptor(
  name='Public',
  full_name='models.Public',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=442,
  serialized_end=506,
  methods=[
  _descriptor.MethodDescriptor(
    name='PrefixSearch',
    full_name='models.Public.PrefixSearch',
    index=0,
    containing_service=None,
    input_type=_SEARCHPARAMS,
    output_type=_ITEM,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PUBLIC)

DESCRIPTOR.services_by_name['Public'] = _PUBLIC


_PRIVATE = _descriptor.ServiceDescriptor(
  name='Private',
  full_name='models.Private',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=508,
  serialized_end=634,
  methods=[
  _descriptor.MethodDescriptor(
    name='Scrape',
    full_name='models.Private.Scrape',
    index=0,
    containing_service=None,
    input_type=_BLOCKINTERVAL,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Status',
    full_name='models.Private.Status',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_SERVERSTATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRIVATE)

DESCRIPTOR.services_by_name['Private'] = _PRIVATE

# @@protoc_insertion_point(module_scope)
